### ISSUE TITLE
Issue Pulling 3+ days

### ISSUE THREAD

**Issue by robeisenrich** [Primayer/XilogDataApiDocs#2]
When I attempt to pull 3 or more days of data from the data/all endpoint it returns an incomplete data set. Pulling two or fewer days works appropriately. Any idea whats happening on the 3+ day data pull?

Sample dates
2022-07-18%2003:30 2022-07-21%2003:30

**Comment by James-Goodbourn** [comment]
Hi @robeisenrich can you provide a serial number of a device you are trying to get data for.

Thanks

**Comment by robeisenrich** [comment]
2001362, Having played with the issue I think the problem is trying to pull data from a day where the logger was not collecting data. For example, if the logger has been recording for 3 days and I pull 4 days of data I would expect the api to return 3 days worth of info however it returns only a partial data set not accounting for the days the logger was recording data.

**Comment by robeisenrich** [comment]
Good morning, the behavior is persisting. This time it is doing it with recent data. If I pull data for the past day from 2001362 I get the most recent day's worth of data. If I pull 2+ days it does not return data for the most recent day. Before this, I was pulling 3 days of data at a time every midnight without issue. However, today it is returning a partial data set. Any idea what's going on here?

**Comment by James-Goodbourn** [comment]
Hi,

I think i see what the problem is here. When a logger is reconfigured the data it recorded during the last configuration is locked, so it starts anew on the new configuration. When getting data from the API. It gets the configuration for the date range selected, then the data.

I see that this logger was configured on 2022-08-09. and has data for 2022-08-09 10:40 - 2022-08-11 12:00.

If you select a start date that is before the start of this configuration it will try and get the data for the previous configuration, which will be from whenever it was configured up to the date of the next configuration.

I will have a look first thing tomorrow, to see if I can change it so it will get all configurations that fall within the date range rather than just the first one that does.

**Comment by robeisenrich** [comment]
It also looks like the json response changes order. Previously it was Flow 2, Flow 1, and Pipe 1 now it is Flow 1, Pipe 1 and Flow 2.
Is the json order not fixed? If so how and when does this order change?

**Comment by James-Goodbourn** [comment]
Hi,

I have made a change to sort the ordering, not sure why it wasnt doing any. I have also made a change to the configuration being retrieved. 

Just going to put all this through test, should be live by Wednesday, I'll let you know when it is.

Regards

**Comment by James-Goodbourn** [comment]
Hi @robeisenrich 

The API Changes have just been made live

**Comment by robeisenrich** [comment]
I am getting an error on my end. My previously successful call to https://xilogdataapi.atriumiot.com/Logger/All/ is now returning 
{'type': 'https://tools.ietf.org/html/rfc7231#section-6.6.1',
 'title': 'An error occurred while processing your request.',
 'status': 500,
 'traceId': '00-7027ef52cd3760438c5b200e746b2060-cb0f98a6fa86a841-00'}

Anything on my end I need to change with the update?

**Comment by James-Goodbourn** [comment]
Hi,

Just checking, and the database server appears to be having some intermittent outages, I have just raised this with them to see whats happening

**Comment by James-Goodbourn** [comment]
Hi @robeisenrich 

The issues with the database should be resolved now.
